-- Never run against a real database. compose.test.yaml owns this tmpfs cluster.
CREATE ROLE lucy_app LOGIN PASSWORD 'synthetic-app-only'
  NOSUPERUSER NOCREATEDB NOCREATEROLE;
CREATE ROLE lucy_public_runtime LOGIN PASSWORD 'synthetic-public-runtime-only'
  NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;
CREATE ROLE lucy_raymond_routine LOGIN PASSWORD 'synthetic-raymond-only'
  NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;
CREATE ROLE lucy_utopia_routine LOGIN PASSWORD 'synthetic-utopia-only'
  NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;
CREATE ROLE lucy_alpha_routine LOGIN PASSWORD 'synthetic-alpha-only'
  NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;
CREATE ROLE lucy_migration NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE
  NOINHERIT NOREPLICATION NOBYPASSRLS;
CREATE ROLE lucy_security_function_owner NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE
  NOINHERIT NOREPLICATION NOBYPASSRLS;
GRANT lucy_security_function_owner TO lucy_owner;
GRANT lucy_migration TO lucy_owner;
GRANT CONNECT ON DATABASE lucy_test TO lucy_app;
GRANT CONNECT ON DATABASE lucy_test TO lucy_public_runtime;
GRANT CONNECT ON DATABASE lucy_test TO
  lucy_raymond_routine, lucy_utopia_routine, lucy_alpha_routine;
CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE SCHEMA lucy AUTHORIZATION lucy_owner;
GRANT USAGE ON SCHEMA lucy TO lucy_app;
GRANT USAGE ON SCHEMA lucy TO lucy_public_runtime;
GRANT USAGE ON SCHEMA lucy TO
  lucy_raymond_routine, lucy_utopia_routine, lucy_alpha_routine;
ALTER DEFAULT PRIVILEGES FOR ROLE lucy_owner IN SCHEMA lucy
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO lucy_app;
ALTER DEFAULT PRIVILEGES FOR ROLE lucy_owner IN SCHEMA lucy
  GRANT USAGE, SELECT ON SEQUENCES TO lucy_app;
